//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @event()
        {
            this.member1 = new HashSet<member>();
            this.moderator = new HashSet<moderator>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public double day { get; set; }
        public int country { get; set; }
        public int id_organizer { get; set; }
        public int id_moderator { get; set; }
        public Nullable<int> id_jury1 { get; set; }
        public Nullable<int> id_jury2 { get; set; }
        public Nullable<int> id_jury3 { get; set; }
    
        public virtual country country1 { get; set; }
        public virtual jury jury { get; set; }
        public virtual jury jury1 { get; set; }
        public virtual jury jury2 { get; set; }
        public virtual member member { get; set; }
        public virtual organizer organizer { get; set; }
        public virtual organizer organizer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> member1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moderator> moderator { get; set; }
    }
}
