//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderator
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string patronymic { get; set; }
        public string gender { get; set; }
        public string Email { get; set; }
        public System.DateTime birthday { get; set; }
        public int country { get; set; }
        public double phone { get; set; }
        public string direction { get; set; }
        public int event_id { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
    
        public virtual @event @event { get; set; }
    }
}
