//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organizer()
        {
            this.@event = new HashSet<@event>();
            this.event1 = new HashSet<@event>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public System.DateTime birthday { get; set; }
        public int country { get; set; }
        public double phone { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> @event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> event1 { get; set; }
    }
}
